'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BShell.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;persistedQuery version=&quot;1.0&quot;&gt;&lt;viewInfo iconSize=&quot;32&quot; stackIconSize=&quot;0&quot; displayName=&quot;Search Result&quot; autoListFlags=&quot;0&quot;&gt;&lt;visibleColumns&gt;&lt;column viewField=&quot;System.ItemNameDisplay&quot;/&gt;&lt;column viewField=&quot;System.DateModified&quot;/&gt;&lt;column viewField=&quot;System.ItemTypeText&quot;/&gt;&lt;column viewField=&quot;System.Size&quot;/&gt;&lt;column viewField=&quot;System.ItemFolderPathDisplayNarrow&quot;/&gt;&lt;/visibleColumns&gt;&lt;sortList&gt;&lt;sort viewField=&quot;System.Search.Rank&quot; direction=&quot;descending&quot;/&gt;&lt;sort viewField=&quot;System.DateModified&quot; direction=&quot;des [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SearchDoc() As String
            Get
                Return ResourceManager.GetString("SearchDoc", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
